const foodPlaces = [
  {
    place: "Kibnesh",
    foods: [
      {
        food: "Egg Sandwich",
        tags: [
          "Meh Mood",
          "Low Budget",
          "Breakfast",
          "Bread Related",
          "Inside Campus",
          "Non Fasting",
        ],
      },
      {
        food: "Ful",
        tags: [
          "Meh Mood",
          "Low Budget",
          "Breakfast",
          "Fasting",
          "Bread Related",
          "Inside Campus",
        ],
      },
      {
        food: "Scrambled Eggs",
        tags: [
          "Meh Mood",
          "Low Budget",
          "Breakfast",
          "Bread Related",
          "Inside Campus",
          "Non Fasting",
        ],
      },
      {
        food: "Firfir",
        tags: [
          "Meh Mood",
          "Low Budget",
          "Breakfast",
          "Injera Related",
          "Inside Campus",
          "Fasting",
        ],
      },
      {
        food: "Dabo Firfir",
        tags: [
          "Meh Mood",
          "Low Budget",
          "Breakfast",
          "Bread Related",
          "Inside Campus",
          "Fasting",
        ],
      },
      {
        food: "Pasta Besego",
        tags: [
          "Meh Mood",
          "Breakfast",
          "Fasting",
          "Low Budget",
          "Bread Related",
          "Inside Campus",
        ],
      },
      {
        food: "Beyaynet",
        tags: [
          "Meh Mood",
          "Lunch",
          "Dinner",
          "Low Budget",
          "High Portion",
          "Inside Campus",
          "Injera Related",
          "Fasting",
        ],
      },
      {
        food: "Denech Bekey",
        tags: [
          "Meh Mood",
          "Lunch",
          "Dinner",
          "Low Budget",
          "Inside Campus",
          "Fasting",
          "High Portion",
          "Injera Related",
        ],
      },
      {
        food: "Denech Alecha",
        tags: [
          "Meh Mood",
          "Lunch",
          "Dinner",
          "Low Budget",
          "Inside Campus",
          "Fasting",
          "High Portion",
          "Injera Related",
        ],
      },
      {
        food: "Misir be Denech",
        tags: [
          "Meh Mood",
          "Lunch",
          "Dinner",
          "Low Budget",
          "Inside Campus",
          "Fasting",
          "High Portion",
          "Injera Related",
        ],
      },
      {
        food: "Misir",
        tags: [
          "Meh Mood",
          "Lunch",
          "Dinner",
          "Low Budget",
          "Inside Campus",
          "Fasting",
          "High Portion",
          "Injera Related",
        ],
      },
      {
        food: "Tegabino",
        tags: [
          "Meh Mood",
          "Lunch",
          "Dinner",
          "Low Budget",
          "Inside Campus",
          "Fasting",
          "High Portion",
          "Injera Related",
        ],
      },
      {
        food: "Gomen Tibs",
        tags: [
          "Meh Mood",
          "Lunch",
          "Dinner",
          "Low Budget",
          "Inside Campus",
          "Fasting",
          "Injera Related",
        ],
      },
      {
        food: "Misir Wot",
        tags: [
          "Meh Mood",
          "Lunch",
          "Dinner",
          "Low Budget",
          "Inside Campus",
          "Fasting",
          "High Portion",
          "Injera Related",
        ],
      },
      {
        food: "Erteb",
        tags: [
          "Meh Mood",
          "Dinner",
          "Low Budget",
          "Inside Campus",
          "Fasting",
          "High Portion",
          "Bread Related",
        ],
      },
    ],
  },
  {
    place: "Teachers",
    foods: [
      {
        food: "Egg Sandwich",
        tags: [
          "Meh Mood",
          "Low Budget",
          "Breakfast",
          "Bread Related",
          "Inside Campus",
          "Non Fasting",
        ],
      },
      {
        food: "Scrambled Eggs",
        tags: [
          "Meh Mood",
          "Low Budget",
          "Breakfast",
          "Bread Related",
          "Inside Campus",
          "Non Fasting",
        ],
      },
      {
        food: "Ful",
        tags: [
          "Meh Mood",
          "Low Budget",
          "Breakfast",
          "Fasting",
          "Bread Related",
          "Inside Campus",
        ],
      },
      {
        food: "Special Ful",
        tags: [
          "Meh Mood",
          "Low Budget",
          "Breakfast",
          "Non Fasting",
          "Bread Related",
          "Inside Campus",
        ],
      },
      {
        food: "Firfir",
        tags: [
          "Meh Mood",
          "Low Budget",
          "Breakfast",
          "Dinner",
          "Injera Related",
          "Inside Campus",
          "Fasting",
        ],
      },
      {
        food: "Special Firfir",
        tags: [
          "Meh Mood",
          "Low Budget",
          "Breakfast",
          "Injera Related",
          "Inside Campus",
          "Non Fasting",
        ],
      },
      {
        food: "Dabo Firfir",
        tags: [
          "Meh Mood",
          "Low Budget",
          "Breakfast",
          "Bread Related",
          "Inside Campus",
          "Fasting",
        ],
      },
      {
        food: "Special Dabo Firfir",
        tags: [
          "Meh Mood",
          "Low Budget",
          "Breakfast",
          "Bread Related",
          "Inside Campus",
          "Non Fasting",
        ],
      },
      {
        food: "Pasta Besego",
        tags: [
          "Meh Mood",
          "Breakfast",
          "Lunch",
          "Dinner",
          "Fasting",
          "Low Budget",
          "Injera Related",
          "Inside Campus",
        ],
      },
      {
        food: "Pasta Be Atkilt",
        tags: [
          "Meh Mood",
          "Breakfast",
          "Lunch",
          "Dinner",
          "Fasting",
          "Low Budget",
          "Injera Related",
          "Inside Campus",
        ],
      },
      {
        food: "Beyaynet",
        tags: [
          "Meh Mood",
          "Lunch",
          "Low Budget",
          "High Portion",
          "Inside Campus",
          "Injera Related",
          "Fasting",
        ],
      },
      {
        food: "Denech Alecha",
        tags: [
          "Meh Mood",
          "Lunch",
          "Dinner",
          "Low Budget",
          "Inside Campus",
          "Fasting",
          "High Portion",
          "Injera Related",
        ],
      },
      {
        food: "Misir",
        tags: [
          "Meh Mood",
          "Lunch",
          "Dinner",
          "Low Budget",
          "Inside Campus",
          "Fasting",
          "High Portion",
          "Injera Related",
        ],
      },
      {
        food: "Menchet",
        tags: [
          "Meh Mood",
          "Lunch",
          "Dinner",
          "High Budget",
          "Inside Campus",
          "Non Fasting",
          "High Portion",
          "Injera Related",
        ],
      },
      {
        food: "Tegabino",
        tags: [
          "Meh Mood",
          "Lunch",
          "Low Budget",
          "Inside Campus",
          "Fasting",
          "High Portion",
          "Injera Related",
        ],
      },
      {
        food: "Shero",
        tags: [
          "Meh Mood",
          "Lunch",
          "Low Budget",
          "Inside Campus",
          "Fasting",
          "High Portion",
          "Injera Related",
        ],
      },
      {
        food: "Key Wot",
        tags: [
          "Meh Mood",
          "Lunch",
          "Dinner",
          "High Budget",
          "Inside Campus",
          "Non Fasting",
          "High Portion",
          "Injera Related",
        ],
      },
      {
        food: "Tibs",
        tags: [
          "Meh Mood",
          "Lunch",
          "Dinner",
          "High Budget",
          "Inside Campus",
          "Non Fasting",
          "High Portion",
          "Injera Related",
        ],
      },
      {
        food: "Dulet",
        tags: [
          "Meh Mood",
          "Lunch",
          "Breakfast",
          "High Budget",
          "Inside Campus",
          "Non Fasting",
          "High Portion",
          "Injera Related",
        ],
      },
      {
        food: "Kekel",
        tags: [
          "Meh Mood",
          "Lunch",
          "Dinner",
          "High Budget",
          "Inside Campus",
          "Non Fasting",
          "High Portion",
          "Injera Related",
        ],
      },
    ],
  },
  {
    place: "KK Green",
    foods: [
      {
        food: "Egg Sandwich",
        tags: [
          "Meh Mood",
          "Low Budget",
          "Breakfast",
          "Lunch",
          "Dinner",
          "Bread Related",
          "Inside Campus",
          "Non Fasting",
        ],
      },
      {
        food: "Scrambled Eggs",
        tags: [
          "Meh Mood",
          "Low Budget",
          "Breakfast",
          "Lunch",
          "Dinner",
          "Bread Related",
          "Inside Campus",
          "Non Fasting",
        ],
      },
      {
        food: "Pasta Be atkilt",
        tags: [
          "Meh Mood",
          "Low Budget",
          "Breakfast",
          "Lunch",
          "Dinner",
          "Bread Related",
          "Inside Campus",
          "Fasting",
        ],
      },
      {
        food: "Erteb",
        tags: [
          "Meh Mood",
          "Dinner",
          "Low Budget",
          "Inside Campus",
          "Fasting",
          "High Portion",
          "Bread Related",
        ],
      },
    ],
  },
  {
    place: "KK Yellow",
    foods: [
      {
        food: "Egg Sandwich",
        tags: [
          "Meh Mood",
          "Low Budget",
          "Breakfast",
          "Lunch",
          "Dinner",
          "Bread Related",
          "Inside Campus",
          "Non Fasting",
        ],
      },
      {
        food: "Scrambled Eggs",
        tags: [
          "Meh Mood",
          "Low Budget",
          "Breakfast",
          "Lunch",
          "Dinner",
          "Bread Related",
          "Inside Campus",
          "Non Fasting",
        ],
      },
      {
        food: "Pasta Be atkilt",
        tags: [
          "Meh Mood",
          "Low Budget",
          "Breakfast",
          "Lunch",
          "Dinner",
          "Bread Related",
          "Inside Campus",
          "Fasting",
        ],
      },
      {
        food: "Ruz Be atkilt",
        tags: [
          "Meh Mood",
          "Low Budget",
          "Breakfast",
          "Lunch",
          "Dinner",
          "Bread Related",
          "Inside Campus",
          "Fasting",
        ],
      },
      {
        food: "Erteb",
        tags: [
          "Meh Mood",
          "Dinner",
          "Low Budget",
          "Inside Campus",
          "Fasting",
          "High Portion",
          "Bread Related",
        ],
      },
      {
        food: "Soya",
        tags: [
          "Meh Mood",
          "Low Budget",
          "Breakfast",
          "Lunch",
          "Dinner",
          "Bread Related",
          "Inside Campus",
          "Fasting",
        ],
      },
      {
        food: "Timatim",
        tags: [
          "Meh Mood",
          "Low Budget",
          "Breakfast",
          "Lunch",
          "Dinner",
          "Bread Related",
          "Inside Campus",
          "Fasting",
        ],
      },
    ],
  },
  {
    place: "Workers",
    foods: [
      {
        food: "Egg Sandwich",
        tags: [
          "Meh Mood",
          "Low Budget",
          "Breakfast",
          "Bread Related",
          "Inside Campus",
          "Non Fasting",
        ],
      },
      {
        food: "Scrambled Eggs",
        tags: [
          "Meh Mood",
          "Low Budget",
          "Breakfast",
          "Bread Related",
          "Inside Campus",
          "Non Fasting",
        ],
      },
      {
        food: "Ful",
        tags: [
          "Meh Mood",
          "Low Budget",
          "Breakfast",
          "Fasting",
          "Bread Related",
          "Inside Campus",
        ],
      },
      {
        food: "Pasta Besego",
        tags: [
          "Meh Mood",
          "Breakfast",
          "Lunch",
          "Dinner",
          "Fasting",
          "Low Budget",
          "Injera Related",
          "Inside Campus",
        ],
      },
      {
        food: "Beyaynet",
        tags: [
          "Meh Mood",
          "Lunch",
          "Low Budget",
          "High Portion",
          "Inside Campus",
          "Injera Related",
          "Fasting",
        ],
      },
      {
        food: "Denech Alecha",
        tags: [
          "Meh Mood",
          "Lunch",
          "Dinner",
          "Low Budget",
          "Inside Campus",
          "Fasting",
          "High Portion",
          "Injera Related",
        ],
      },
      {
        food: "Misir",
        tags: [
          "Meh Mood",
          "Lunch",
          "Dinner",
          "Low Budget",
          "Inside Campus",
          "Fasting",
          "High Portion",
          "Injera Related",
        ],
      },
      {
        food: "Menchet",
        tags: [
          "Meh Mood",
          "Lunch",
          "Dinner",
          "High Budget",
          "Inside Campus",
          "Non Fasting",
          "High Portion",
          "Injera Related",
        ],
      },
      {
        food: "Tegabino",
        tags: [
          "Meh Mood",
          "Lunch",
          "Low Budget",
          "Inside Campus",
          "Fasting",
          "High Portion",
          "Injera Related",
        ],
      },
      {
        food: "Key Wot",
        tags: [
          "Meh Mood",
          "Lunch",
          "Dinner",
          "High Budget",
          "Inside Campus",
          "Non Fasting",
          "High Portion",
          "Injera Related",
        ],
      },
      {
        food: "Tibs",
        tags: [
          "Meh Mood",
          "Lunch",
          "Dinner",
          "High Budget",
          "Inside Campus",
          "Non Fasting",
          "High Portion",
          "Injera Related",
        ],
      },
    ],
  },
  {
    place: "Yordi's",
    foods: [
      {
        food: "Breakfast Combo",
        tags: [
          "Non Fasting",
          "High Portion",
          "Explore Mood",
          "Outside Campus",
          "High Budget",
          "Breakfast",
        ],
      },
      {
        food: "Kuanta Firfir",
        tags: [
          "Non Fasting",
          "High Portion",
          "Explore Mood",
          "Outside Campus",
          "High Budget",
          "Breakfast",
          "Lunch",
          "Dinner",
        ],
      },
      {
        food: "Dulet",
        tags: [
          "Non Fasting",
          "High Portion",
          "Explore Mood",
          "Outside Campus",
          "High Budget",
          "Breakfast",
          "Lunch",
          "Dinner",
        ],
      },
      {
        food: "Scrambled Eggs",
        tags: [
          "Non Fasting",
          "High Portion",
          "Explore Mood",
          "Outside Campus",
          "High Budget",
          "Breakfast",
          "Lunch",
          "Dinner",
        ],
      },
      {
        food: "Special Ful",
        tags: [
          "Non Fasting",
          "High Portion",
          "Explore Mood",
          "Outside Campus",
          "High Budget",
          "Breakfast",
          "Lunch",
          "Dinner",
        ],
      },
      {
        food: "Tuna Firfir",
        tags: [
          "Fasting",
          "High Portion",
          "Explore Mood",
          "Outside Campus",
          "High Budget",
          "Breakfast",
          "Lunch",
          "Dinner",
        ],
      },
      {
        food: "Soya Firfir",
        tags: [
          "Fasting",
          "High Portion",
          "Explore Mood",
          "Outside Campus",
          "High Budget",
          "Breakfast",
          "Lunch",
          "Dinner",
        ],
      },
      {
        food: "Injera Firfir",
        tags: [
          "Fasting",
          "High Portion",
          "Explore Mood",
          "Outside Campus",
          "High Budget",
          "Breakfast",
          "Lunch",
          "Dinner",
        ],
      },
      {
        food: "Derkosh Firfir",
        tags: [
          "Fasting",
          "High Portion",
          "Explore Mood",
          "Outside Campus",
          "High Budget",
          "Breakfast",
          "Lunch",
          "Dinner",
        ],
      },
      {
        food: "Ful",
        tags: [
          "Fasting",
          "High Portion",
          "Explore Mood",
          "Outside Campus",
          "High Budget",
          "Breakfast",
          "Lunch",
          "Dinner",
        ],
      },
      {
        food: "Special Combo",
        tags: [
          "Non Fasting",
          "High Portion",
          "Explore Mood",
          "Outside Campus",
          "High Budget",
          "Breakfast",
          "Lunch",
          "Dinner",
        ],
      },
      {
        food: "Tibs",
        tags: [
          "Non Fasting",
          "High Portion",
          "Explore Mood",
          "Outside Campus",
          "High Budget",
          "Breakfast",
          "Lunch",
          "Dinner",
        ],
      },
      {
        food: "Key Wot",
        tags: [
          "Non Fasting",
          "High Portion",
          "Explore Mood",
          "Outside Campus",
          "High Budget",
          "Breakfast",
          "Lunch",
          "Dinner",
        ],
      },
      {
        food: "Minchet",
        tags: [
          "Non Fasting",
          "High Portion",
          "Explore Mood",
          "Outside Campus",
          "High Budget",
          "Breakfast",
          "Lunch",
          "Dinner",
        ],
      },
      {
        food: "Bozena Shero",
        tags: [
          "Non Fasting",
          "High Portion",
          "Explore Mood",
          "Outside Campus",
          "High Budget",
          "Breakfast",
          "Lunch",
          "Dinner",
        ],
      },
      {
        food: "Misir Besega",
        tags: [
          "Non Fasting",
          "High Portion",
          "Explore Mood",
          "Outside Campus",
          "High Budget",
          "Breakfast",
          "Lunch",
          "Dinner",
        ],
      },
      {
        food: "Pasta Besega",
        tags: [
          "Non Fasting",
          "High Portion",
          "Explore Mood",
          "Outside Campus",
          "High Budget",
          "Breakfast",
          "Lunch",
          "Dinner",
        ],
      },
      {
        food: "Ruz Besega",
        tags: [
          "Non Fasting",
          "High Portion",
          "Explore Mood",
          "Outside Campus",
          "High Budget",
          "Breakfast",
          "Lunch",
          "Dinner",
        ],
      },
      {
        food: "Yegna Special",
        tags: [
          "Fasting",
          "High Portion",
          "Explore Mood",
          "Outside Campus",
          "High Budget",
          "Breakfast",
          "Lunch",
          "Dinner",
        ],
      },
      {
        food: "Yetsom Combo",
        tags: [
          "Fasting",
          "High Portion",
          "Explore Mood",
          "Outside Campus",
          "High Budget",
          "Breakfast",
          "Lunch",
          "Dinner",
        ],
      },
      {
        food: "Timatim Lebleb",
        tags: [
          "Fasting",
          "High Portion",
          "Explore Mood",
          "Outside Campus",
          "High Budget",
          "Breakfast",
          "Lunch",
          "Dinner",
        ],
      },
      {
        food: "Shero",
        tags: [
          "Fasting",
          "High Portion",
          "Explore Mood",
          "Outside Campus",
          "High Budget",
          "Breakfast",
          "Lunch",
          "Dinner",
        ],
      },
      {
        food: "Misir Wot",
        tags: [
          "Fasting",
          "High Portion",
          "Explore Mood",
          "Outside Campus",
          "High Budget",
          "Breakfast",
          "Lunch",
          "Dinner",
        ],
      },
      {
        food: "Tegabino",
        tags: [
          "Fasting",
          "High Portion",
          "Explore Mood",
          "Outside Campus",
          "High Budget",
          "Breakfast",
          "Lunch",
          "Dinner",
        ],
      },
      {
        food: "Gomen Kitfo",
        tags: [
          "Non Fasting",
          "High Portion",
          "Explore Mood",
          "Outside Campus",
          "High Budget",
          "Breakfast",
          "Lunch",
          "Dinner",
        ],
      },
      {
        food: "Pasta Besego",
        tags: [
          "Fasting",
          "High Portion",
          "Explore Mood",
          "Outside Campus",
          "High Budget",
          "Breakfast",
          "Lunch",
          "Dinner",
        ],
      },
      {
        food: "Ruz Besego",
        tags: [
          "Fasting",
          "High Portion",
          "Explore Mood",
          "Outside Campus",
          "High Budget",
          "Breakfast",
          "Lunch",
          "Dinner",
        ],
      },
      {
        food: "Pasta Betuna",
        tags: [
          "Fasting",
          "High Portion",
          "Explore Mood",
          "Outside Campus",
          "High Budget",
          "Breakfast",
          "Lunch",
          "Dinner",
        ],
      },
      {
        food: "Ruz Betuna",
        tags: [
          "Fasting",
          "High Portion",
          "Explore Mood",
          "Outside Campus",
          "High Budget",
          "Breakfast",
          "Lunch",
          "Dinner",
        ],
      },
      {
        food: "Pasta Beatkilt",
        tags: [
          "Fasting",
          "High Portion",
          "Explore Mood",
          "Outside Campus",
          "High Budget",
          "Breakfast",
          "Lunch",
          "Dinner",
        ],
      },
      {
        food: "Ruz Beatkilt",
        tags: [
          "Fasting",
          "High Portion",
          "Explore Mood",
          "Outside Campus",
          "High Budget",
          "Breakfast",
          "Lunch",
          "Dinner",
        ],
      },
      {
        food: "Atkilt",
        tags: [
          "Fasting",
          "High Portion",
          "Explore Mood",
          "Outside Campus",
          "High Budget",
          "Breakfast",
          "Lunch",
          "Dinner",
        ],
      },
      {
        food: "Kings Burger",
        tags: [
          "Non Fasting",
          "High Portion",
          "Explore Mood",
          "Outside Campus",
          "High Budget",
          "Lunch",
          "Dinner",
        ],
      },
      {
        food: "Special Burger",
        tags: [
          "Non Fasting",
          "High Portion",
          "Explore Mood",
          "Outside Campus",
          "High Budget",
          "Lunch",
          "Dinner",
        ],
      },
      {
        food: "Cheese Burger",
        tags: [
          "Non Fasting",
          "High Portion",
          "Explore Mood",
          "Outside Campus",
          "High Budget",
          "Lunch",
          "Dinner",
        ],
      },
      {
        food: "Normal Burger",
        tags: [
          "Non Fasting",
          "High Portion",
          "Explore Mood",
          "Outside Campus",
          "High Budget",
          "Lunch",
          "Dinner",
        ],
      },
      {
        food: "Beef Wrap",
        tags: [
          "Non Fasting",
          "High Portion",
          "Explore Mood",
          "Outside Campus",
          "High Budget",
          "Lunch",
          "Dinner",
        ],
      },
      {
        food: "Club Sandwich",
        tags: [
          "Non Fasting",
          "High Portion",
          "Explore Mood",
          "Outside Campus",
          "High Budget",
          "Lunch",
          "Dinner",
        ],
      },
      {
        food: "Egg Sandwich",
        tags: [
          "Non Fasting",
          "High Portion",
          "Explore Mood",
          "Outside Campus",
          "High Budget",
          "Breakfast",
          "Lunch",
          "Dinner",
        ],
      },
      {
        food: "Tuna Sandwich",
        tags: [
          "Fasting",
          "High Portion",
          "Explore Mood",
          "Outside Campus",
          "High Budget",
          "Breakfast",
          "Lunch",
          "Dinner",
        ],
      },
      {
        food: "Atkilt Sandwich",
        tags: [
          "Fasting",
          "High Portion",
          "Explore Mood",
          "Outside Campus",
          "High Budget",
          "Breakfast",
          "Lunch",
          "Dinner",
        ],
      },
      {
        food: "French Fries",
        tags: [
          "Fasting",
          "High Portion",
          "Explore Mood",
          "Outside Campus",
          "High Budget",
          "Breakfast",
          "Lunch",
          "Dinner",
        ],
      },
    ],
  },
];

export default foodPlaces;
